global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'statsd'
    metrics_path: /metrics
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: 'airflow-webserver'
    metrics_path: /metrics
    static_configs:
      - targets: ['airflow-webserver:8080']
